//
//  ViewController.swift
//  Bulmaca
//
//  Created by Hasan Basri Komser on 5.12.2022.
//

import UIKit

class ViewController: UIViewController {
    
    @IBOutlet weak var clueLabel: UILabel!
    @IBOutlet weak var scoreLabel: UILabel!
    @IBOutlet weak var guessTextField: UITextField!
    var synonymWord = [
        "ALFABE":"ABECE",
        "ABİDE":"ANIT",
        "ACIMA":"MERHAMET",
        "AÇIKGÖZ":"KURNAZ",
        "AD":"İSİM",
        "ADALE":"KAS",
        "ADET":"TANE",
        "ADIL":"ZAMİR",
        "ADİ":"BAYAĞI",
        "AFERİN":"BRAVO",
        "AFFETMEK":"BAĞIŞLAMAK",
        "AHENK":"UYUM",
        "AKIL":"US",
        "AKSİ":"TERS",
        "AL":"KIRMIZI",
        "ALAKA":"İLGİ",
        "ALAZ":"ALEV",
        "ALELADE":"SIRADAN",
        "ALLAH":"TANRI",
        "AMA":"FAKAT",
        "AMAÇ":"EREK",
        "AMADE":"HAZIR",
        "AMELE":"İŞÇİ",
        "AMEL":"İŞ",
        "ANA":"ANNE",
        "ANI":"HATIRA",
        "ANİDEN":"BİRDEN",
        "ANLAM" : "MANA",
        "ANLATIM" : "İFADE",
        "ANT" : "YEMİN",
        "APSE" : "İLTİHAP",
        "ARAÇ" : "VASITA",
        "ARIZA" : "BOZUKLUK",
        "ARMAĞAN" : "HEDİYE",
        "ARKA" : "GERİ",
        "ART" : "ARKA",
        "ARZU" : "İSTEK",
        "ASIR" : "YÜZYIL",
        "ASİL" : "SOYLI",
        "AŞ" : "YEMEK",
        "AŞIRMAK" : "ÇALMAK",
        "ATA" : "CET",
        "ATAK" : "GİRİŞKEN",
        "ATÖLYE" : "İŞLİK",
        "AVARE" : "SERSERİ",
        "AYAKYOLU" : "HELA",
        "AYLAK":"SERSERİ",
        "AYRAÇ" : "PARANTEZ",
        "AYRICALIK" : "İMTİYAZ",
        "AZA" : "ÜYE",
        "ACEMİ" : "TOY",
        "ADALET" : "HAK",
        "AKA" : "BÜYÜK",
        "ALENİ" : "AÇIK",
        "ARA" : "FASILA",
        "AYAKKABI" : "PABUÇ",
        "BAĞIŞLAMAK":"AFFETMEK",
        "BAĞNAZ" : "YOBAZ",
        "BAKIŞ" : "NAZAR",
        "BARIŞ" : "SULH",
        "BASIMEVİ" : "MATBAA",
        "BASİT" : "YALIN",
        "BAŞKALDIRI" : "İSYAN",
        "BAŞKAN" : "REİS",
        "BAŞKENT" : "BAŞŞEHİR",
        "BAŞVURU" : "MÜRACAAT",
        "BATI" : "GARP",
        "BAYAĞI" : "ADİ",
        "BAYINDIR" : "MAMUR",
        "BAYINDIRLIK" : "İMAR",
        "BAYTAR" : "VETERİNER",
        "BAZEN" : "KİMİ",
        "BEDAVA" : "PARASIZ",
        "BEDEN" : "GÖVDE",
        "BEĞENİ" : "ZEVK",
        "BELDE" : "ŞEHİR",
        "BELGE" : "VESİKA",
        "BELLEK" : "HAFIZA",
        "BENCİL" : "EGOİST",
        "BENLİK" : "KİŞİLİK",
        "BERABER" : "BİRLİKTE",
        "BEREKET" : "BOLLUK",
        "BERRAK" : "DURU",
        "BESİN" : "GIDA",
        "BEYANAT" : "DEMEÇ",
        "BEYAZ" : "AK",
        "BEYGİR" : "AT",
        "BEYHUDE" : "BOŞUNA",
        "BİÇARE" : "ZAVALLI",
        "BİÇİM" :"ŞEKİL",
        "BİLAKİS" : "TERSİNE",
        "BİLGİN" : "ALİM",
        "BİLGİSİZ" : "CAHİL",
        "BİLHASSA" : "ÖZELLİKLE",
        "BİLİM" : "İLİM",
        "BİLİNÇ" : "ŞUUR",
        "BİNA" : "YAPI",
        "BİRDEN" : "ANİ",
        "BİRDENBİRE" : "ANİDEN",
        "BİREY" : "FERT",
        "BİRİCİK" : "TEK",
        "BİTKİ" : "NEBAT",
        "BOYLAM" : "MERİDYEN",
        "BOZKIR" : "STEP",
        "BUCAK" : "NAHİYE",
        "BUĞU" : "BUHAR",
        "BUHRAN" : "BUNALIM",
        "BUYRUK" : "EMİR",
        "BÜRO" : "OFİS",
        "BACI" : "KIZ KARDEŞ",
        "BAŞ" : "KAFA",
        "CAHİL" : "BİLGİSİZ",
        "CAKA" : "GÖSTERİŞ",
        "CAMEKAN" : "VİTRİN",
        "CANLI" : "DİRİ",
        "CAZİBE" : "ÇEKİM",
        "CEHALET" : "BİLGİSİZLİK",
        "CELSE" : "OTURUM",
        "CENK" : "SAVAŞ",
        "CENUP" : "GÜNEY",
        "CERAHAT" : "İRİN",
        "CERRAH" : "OPERATÖR",
        "CESUR" : "YÜREKLİ",
        "CET" : "ATA",
        "CEVAP" : "YANIT",
        "CEVİZ" : "KOZ",
        "CILIZ" : "SISKA",
        "CİDDİ" : "AĞIRBAŞLI",
        "CİHAZ" : "AYGIT",
        "CİHET" : "YÖN",
        "CİLT" :"TEN",
        "CİMRİ" : "PİNTİ",
        "CİN" : "TÜR",
        "CİVAR" : "YÖRE",
        "CÖMERT" : "ELİ AÇIK",
        "CÜMLE" : "TÜMCE",
        "CİNS" : "TÜR",
        "ÇABUK" : "ACELE",
        "ÇAĞ" : "DEVİR",
        "ÇAĞDAŞ" : "MODERN",
        "ÇAĞRI" : "DAVET",
        "ÇEHRE" : "YÜZ",
        "ÇEŞİT" : "TÜR",
        "ÇEVİRİ" : "TERCÜME",
        "ÇIĞLIK" : "FERYAT",
        "ÇILGIN" : "DELİ",
        "ÇİZELGE" : "CETVEL",
        "ÇOĞUNLUK" : "EKSERİYET",
        "ÇOK" : "FAZLA",
        "ÇAMUR" : "BALÇIK",
        "ÇARE" : "DEVA",
        "DAHİL" : "İÇ",
        "DAİMİ" : "SÜREKLİ",
        "DARBE" : "VURUŞ",
        "DARGIN" : "KÜS",
        "DARILMAK" : "KÜSMEK",
        "DAVET" : "ÇAĞRI",
        "DEFA" : "KEZ",
        "DEĞER" : "KIYMET",
        "DEĞERLİ" : "KIYMETLİ",
        "DEĞNEK" : "SOPA",
        "DELİ" : "ÇILGIN",
        "DELİL" : "KANIT",
        "DENEME" : "TECRÜBE",
        "DENETİM" : "KONTROL",
        "DENEYİM" : "TECRÜBE",
        "DEPREM" : "ZERZELE",
        "DERGİ" : "MECMUA",
        "DERHAL" : "HEMEN",
        "DERİ" : "TEN",
        "DERSLİK" : "SINIF",
        "DEVAMLI" : "SÜREKLİ",
        "DEVİNİM" : "HAREKET",
        "DEVİR" : "TUR",
        "DEVRE" : "DÖNEM",
        "DIŞALIM" : "İTHALAT",
        "DIŞSATIM" : "İHRACAT",
        "DİĞER" : "BAŞKA",
        "DİL" : "LİSAN",
        "DİLBİLGİSİ" : "GRAMER",
        "DİRİ" : "CANLI",
        "DİZE" : "MISRA",
        "DOĞA" : "TABİAT",
        "DOĞAL" : "TABİİ",
        "DOĞU" : "ŞARK",
        "DOKTOR" : "HEKİM",
        "DONUK" : "MAT",
        "DORUK" : "ZİRVE",
        "DÖNEMEÇ" : "VİRAJ",
        "DÖŞEK" : "YATAK",
        "DURU" : "BERRAK",
        "DURUM" : "VAZİYET",
        "DUYGU" : "HİS",
        "DÜŞ" : "RÜYA",
        "DÜŞÜNCE" : "FİKİR",
        "DÜZEN" : "SEVİYE",
        "DÜZMECE" : "SAHTE",
        "DÜZYAZI" : "NESİR",
        "DİLEK" : "İSTEK",
        "DİZİ" : "SIRA",
        "DOST" : "ARKADAŞ",
        "EBAT" : "BOYUT",
        "EBEDİ" : "SONSUZ",
        "EDAT" : "İLGEÇ",
        "EGOİST" : "BENCİL",
        "EHEMMİYET" : "ÖNEM",
        "EK" :"İLAVE",
        "EKLEM" : "MAFSAL",
        "EKONOMİ" : "İKTİSAT",
        "ELBİSE" :"GİYSİ",
        "EMİR" : "BUYRUK",
        "EMNİYET" : "GÜVENLİK",
        "ENDER" : "NADİR",
        "ENDİŞE" :"KAYGI",
        "ENDÜSTRİ" : "SANAYİ",
        "ENKAZ" : "YIKINTI",
        "ENLEM" : "PARALEL",
        "ENTARİ" : "GİYSİ",
        "ENTERESAN" : "İLGİNÇ",
        "EREK" : "AMAÇ",
        "ESAS" : "TEMEL",
        "ESER" : "YAPIT",
        "ESİR" :"TUTSAK",
        "ETKİ" : "TESİR",
        "ETRAF" : "ÇEVRE",
        "EVVEL" : "ÖNCE",
        "EYLEM" : "FİİL",
        "EYLMESİ" : "FİİLİMSİ",
        "EV" : "KONUT",
        "EDEBİYAT" : "YAZIN",
        "EDA" : "VERME",
        "FAALİYET" : "ETKİNLİK",
        "FAKİR" : "YOKSUL",
        "FAKTÖR" : "UNSUR",
        "FARK" : "AYRIM",
        "FASILA" : "ARA",
        "FAYDA" : "YARAR",
        "FAZLA" : "ÇOK",
        "FENA" : "KÖTÜ",
        "FERT" : "BİREY",
        "FEZA" : "UZAY",
        "FİİL" : "EYLEM",
        "FİKİR" : "DÜŞÜNCE",
        "FİLE" : "AĞ",
        "FÜZE" : "ROKET",
        "FELÇ" : "NÜZUL",
        "FER" : "IŞIK",
        "FAİZ" : "NEMA",
        "GARİP" : "ACAYİP",
        "GARP" : "BATI",
        "GAYE" : "AMAÇ",
        "GAYRET" : "ÇABA",
        "GEBE" : "HAMİLE",
        "GELECEK" : "İSTİKBAL",
        "GELENEK" : "ANANE",
        "GENE" : "YİNE",
        "GENEL" : "UMUMİ",
        "GERİ" : "ART",
        "GIDA" : "BESİN",
        "GİYSİ" : "ELBİSE",
        "GİZ" : "SIR",
        "GİZLİ" : "SAKLI",
        "GÖREV" : "VAZİFE",
        "GÖVDE" : "BEDEN",
        "GRAMER" : "DİLBİLGİSİ",
        "GÜÇ" : "KUVVET",
        "GÜÇLÜ" : "KUVVETLİ",
        "GÜLDÜRÜ" : "KOMEDİ",
        "GÜLÜNÇ" : "KOMİK",
        "GÜNEY" : "CENUP",
        "GÜVEN" : "İTİMAT",
        "GÜZ" : "SONBAHAR",
        "GÖZLEM" : "RASAT",
        "GÖKYÜZÜ" : "SEMA",
        "GEZMEK" : "DOLAŞMAK",
        "ILICA" : "KAPLICA",
        "IRAK" : "UZAK",
        "IRGAT" : "RENÇBER",
        "IRK" : "SOY",
        "IRA" : "KARAKTER",
        "IRMAK" : "NEHİR",
        "HAL" : "DURUM",
        "HALBUKİ" : "OYSA",
        "HAM" : "OLMAMIŞ",
        "HANE" : "EV",
        "HAREKET" : "DEVİNİM",
        "HARİÇ" : "DIŞ",
        "HARP" : "SAVAŞ",
        "HASİS" : "CİMRİ",
        "HASRET" : "ÖZLEM",
        "HASSAS" : "DUYGULU",
        "HATIRA" : "ANI",
        "HAYAL" : "DÜŞ",
        "HAYAT" : "YAŞAM",
        "HAYSİYET" : "ONUR",
        "HEDİYE" : "ARMAĞAN",
        "HEKİM" : "DOKTOR",
        "HELA" : "TUVALET",
        "HEMEN" : "DERHAL",
        "HİDDET" : "ÖFKE",
        "HİKAYE" : "ÖYKÜ",
        "HİSSE" : "PAY",
        "HUDUT" : "SINIR",
        "HUSUSİ" : "ÖZEL",
        "HÜR" : "ÖZGÜR",
        "HISIM" : "AKRABA",
        "HASIM" : "DÜŞMAN",
        "HADİSE" : "OLAY",
    ]
    
    var wordsArray : [String] = [""]
    var synonymArray : [String] = [""]
    var score = 0
    
    // MARK: - CODING
    
    override func viewDidLoad() {
        super.viewDidLoad()
        guessTextField.text = nil
        synonymArray = [String](synonymWord.values)
        clueLabel.text = synonymArray.randomElement()
        scoreLabel.text = "SKOR: 0"
    }
    
    
    @IBAction func enterButtonClicked(_ sender: Any) {
        getQuestion()
        if guessTextField.text != guessTextField.text?.uppercased() {
            
            makeDisplayActionSheet()
        }
    }
    
    func getQuestion () {
        
        if let guess = synonymWord[guessTextField.text!] {
            if guess.uppercased() == clueLabel.text {
                clueLabel.text = synonymArray.randomElement()
                guessTextField.text = ""
                score = score + 10
                scoreLabel.text = "SKOR: \(score)"
            }
        }
    }
    func makeDisplayActionSheet() {
        let alert = UIAlertController(title: "UYARI", message: "Kelimenin Tüm Harflerini Büyük Olacak Şekilde Giriniz.", preferredStyle: .actionSheet)
        let firstButton = UIAlertAction(title: "Tamam", style: .default) { (action) in
        }
        alert.addAction(firstButton)
        present(alert, animated: true) {
        }
    }
}






